version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  pharma-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pharma-ai
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped

volumes:
  ollama_data: