name: pharma-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=21.0
  - pip:
    - streamlit==1.26.0
    - sentence-transformers==2.3.0
    - requests==2.31.0
    - pandas==2.0.3
    - numpy==1.24.4
    - pytest==7.4.0
    - pytest-mock==3.11.1
    - pydantic==2.3.0
    - black==23.7.0
    - isort==5.12.0
    - mypy==1.5.1
    - flake8==6.1.0
    - python-dotenv==1.0.0
    - scikit-learn==1.3.0
    - tqdm==4.66.1
    - nltk==3.8.1
    - jsonschema==4.19.0